# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Слаг')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
            ],
            options={
                'db_table': 'slides',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название организации')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название презентации')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Слаг')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Organisation')),
            ],
            options={
                'db_table': 'presentations',
            },
        ),
        migrations.AddField(
            model_name='coreslide',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Presentation'),
        ),
    ]
