# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_number', models.IntegerField(verbose_name='Номер варианта ответа')),
                ('text', models.CharField(max_length=64, verbose_name='Текст ответа')),
                ('is_right', models.BooleanField(verbose_name='Является правильным ответом')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answers_type', models.CharField(choices=[('YN', 'Yes_or_NO'), ('L', 'List'), ('LC', 'List_and_comment')], max_length=2, verbose_name='Тип ответов')),
                ('presentation_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.Presentation', verbose_name='Номер презентации')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.Answer', verbose_name='Ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.ProjectUser', verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'user_answers',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.Question'),
        ),
    ]
