# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 20:51
from __future__ import unicode_literals

from django.db import migrations


def create_ikea(apps, schema_editor):
    # We can't import the Organisation model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Organisation = apps.get_model("presentations", "Organisation")
    Organisation.objects.get_or_create(name='Икеа', slug='ikea')


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_ikea)
    ]
