# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20160202_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.Organisation'),
        ),
    ]
