# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20160131_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreslide',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='presentation_number',
        ),
        migrations.AddField(
            model_name='coreslide',
            name='presentation_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='presentations.Presentation', verbose_name='Презентация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coreslide',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentations.Question'),
        ),
    ]
