# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20160210_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
