# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_presentation_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreslide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
