# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20160201_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreslide',
            old_name='presentation_number',
            new_name='presentation',
        ),
    ]
