# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0004_auto_20160314_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreslide',
            name='image',
            field=models.ImageField(upload_to='cores_images'),
        ),
    ]
