# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0004_auto_20160202_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='has_comment',
            field=models.BooleanField(default=0, verbose_name='Ответ с комментарием'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_type',
            field=models.CharField(choices=[('M', 'Multivariate response'), ('U', 'Univariate response')], max_length=2, verbose_name='Тип ответов'),
        ),
    ]
