# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0005_auto_20160209_1849'),
        ('presentations', '0002_auto_20160210_2051'),
    ]

    operations = [
    ]
