# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 20:52
from __future__ import unicode_literals

from django.db import migrations


def update_old_question_choices(apps, schema_editor):
    Question = apps.get_model("presentations", "Question")
    for q in Question.objects.filter(answers_type='M'):
        q.answers_type = 'multi'
        q.save()
    for q in Question.objects.filter(answers_type='U'):
        q.answers_type = 'single'
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0007_auto_20160301_2049'),
    ]

    operations = [
        migrations.RunPython(update_old_question_choices)
    ]
