# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0008_auto_20160301_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentations.Organisation'),
        ),
    ]
