# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0006_auto_20160323_0903'),
        ('presentations', '0008_auto_20160301_2052'),
    ]

    operations = [
    ]
