# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0009_question_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'ответы'},
        ),
        migrations.AlterModelOptions(
            name='coreslide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'слайды'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Презентация', 'verbose_name_plural': 'презентации'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'ответы пользователей'},
        ),
    ]
