# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0010_auto_20160321_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер вопроса'),
        ),
    ]
