# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0013_remove_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='position',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
