# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0014_auto_20160321_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.Organisation', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='position',
            field=models.IntegerField(default=0, editable=False, verbose_name='Позиция'),
        ),
    ]
