# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0015_auto_20160321_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreslide',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coreslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='coreslide',
            name='position',
            field=models.IntegerField(default=0, editable=False, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='coreslide',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentations.Question', verbose_name='Вопрос'),
        ),
    ]
