# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import presentations.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0016_auto_20160322_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='has_comment',
            field=models.BooleanField(default=False, verbose_name='Ответ с комментарием'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Является правильным ответом'),
        ),
        migrations.AlterField(
            model_name='coreslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=presentations.models.get_upload_path, verbose_name='Изображение'),
        ),
    ]
