# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0017_auto_20160330_2119'),
        ('presentations', '0009_merge'),
    ]

    operations = [
    ]
