# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import presentations.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0018_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreslide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'слайды'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AlterField(
            model_name='coreslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=presentations.models.get_upload_path, verbose_name='Изображение'),
        ),
    ]
