# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'project_users',
            },
        ),
        migrations.CreateModel(
            name='UserPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Presentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.ProjectUser')),
            ],
            options={
                'db_table': 'user_presentations',
            },
        ),
        migrations.CreateModel(
            name='UserSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.CoreSlide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.ProjectUser')),
            ],
            options={
                'db_table': 'user_slides',
            },
        ),
    ]
