# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='presentations.Organisation'),
            preserve_default=False,
        ),
    ]
