# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
    ]
