# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0002_projectuser_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
