# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 18:39
from __future__ import unicode_literals

from django.db import migrations


def add_test_user(apps, schema_editor):
    # We can't import the Organisation model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ProjectUser = apps.get_model("user_interface", "ProjectUser")
    try:
        ProjectUser.objects.get(name='tester')
    except ProjectUser.DoesNotExist:
        ProjectUser.objects.create(name='tester', organisation_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_auto_20160202_1534'),
    ]

    operations = [
        migrations.RunPython(add_test_user)
    ]

