# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0004_auto_20160303_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresentation',
            name='passage_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Вреся прохождения'),
        ),
    ]
