# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0005_userpresentation_passage_time'),
        ('user_interface', '0002_auto_20160330_1849'),
    ]

    operations = [
    ]
