# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0006_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpresentation',
            options={'verbose_name': 'Завершенные презентации', 'verbose_name_plural': 'Завершенные презентации'},
        ),
    ]
