# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 17:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_interface', '0007_auto_20160414_0340'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projectuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='name',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='presentations.Organisation'),
        ),
    ]
